import { DataType } from "./data-type"

export const testData: DataType[] = [
    {
        login: "lucywho",
        avatar_url: "https://avatars.githubusercontent.com/u/30469302?v=4",
        html_url: "https://github.com/lucywho",
        name: "Lucy Toman",
        blog: "lucysco.de",
        location: "Berlin, Germany",
        bio: "Full-stack web developer with a background in project and product management.\r\nGetting back into the coding saddle after a couple of years out to learn German.",
        twitter_username: null,
        public_repos: 38,
        followers: 9,
        following: 8,
        created_at: "2017-07-26T12:59:44Z",
    },
    {
        login: "timd",
        avatar_url: "https://avatars.githubusercontent.com/u/6924?v=4",
        html_url: "https://github.com/timd",
        name: "Tim Duckett",
        blog: "https://trashpanda.cc",
        location: "Berlin, Deutschland",
        bio: "CTO, economicly migratory Inselaffe, Kohlenstoffbasierte Zweibeiner Säugetiere\r\n",
        twitter_username: null,
        public_repos: 136,
        followers: 108,
        following: 0,
        created_at: "2008-04-12T11:25:16Z",
    },
    {
        login: "Alpha",
        avatar_url: "https://avatars.githubusercontent.com/u/15315424?v=4",
        html_url: "https://github.com/Alpha",
        name: "Alpha",
        blog: "",
        location: "Everywhere",
        bio: null,
        twitter_username: null,
        public_repos: 2,
        followers: 1,
        following: 0,
        created_at: "2015-10-25T23:05:32Z",
    },
    {
        login: "beta",
        avatar_url: "https://avatars.githubusercontent.com/u/5000910?v=4",
        html_url: "https://github.com/beta",
        name: "Beta Kuang",
        blog: "https://betakuang.me",
        location: "nil",
        bio: "Web & app developer",
        twitter_username: "betakuang",
        public_repos: 66,
        followers: 105,
        following: 44,
        created_at: "2013-07-13T03:21:42Z",
    },

    {
        login: "charlie",
        avatar_url: "https://avatars.githubusercontent.com/u/1763?v=4",
        html_url: "https://github.com/charlie",
        name: "Charles Hornberger",
        blog: "",
        location: "Berlin",
        bio: null,
        twitter_username: null,
        public_repos: 11,
        followers: 4,
        following: 0,
        created_at: "2008-02-29T17:24:19Z",
    },
]
