const testData: object[] = [
    {
        login: "lucywho",
        id: 30469302,
        node_id: "MDQ6VXNlcjMwNDY5MzAy",
        avatar_url: "https://avatars.githubusercontent.com/u/30469302?v=4",
        gravatar_id: "",
        url: "https://api.github.com/users/lucywho",
        html_url: "https://github.com/lucywho",
        followers_url: "https://api.github.com/users/lucywho/followers",
        following_url:
            "https://api.github.com/users/lucywho/following{/other_user}",
        gists_url: "https://api.github.com/users/lucywho/gists{/gist_id}",
        starred_url:
            "https://api.github.com/users/lucywho/starred{/owner}{/repo}",
        subscriptions_url: "https://api.github.com/users/lucywho/subscriptions",
        organizations_url: "https://api.github.com/users/lucywho/orgs",
        repos_url: "https://api.github.com/users/lucywho/repos",
        events_url: "https://api.github.com/users/lucywho/events{/privacy}",
        received_events_url:
            "https://api.github.com/users/lucywho/received_events",
        type: "User",
        site_admin: false,
        name: "Lucy Toman",
        company: null,
        blog: "lucysco.de",
        location: "Berlin, Germany",
        email: null,
        hireable: null,
        bio: "Full-stack web developer with a background in project and product management.\r\nGetting back into the coding saddle after a couple of years out to learn German.",
        twitter_username: null,
        public_repos: 38,
        public_gists: 0,
        followers: 9,
        following: 8,
        created_at: "2017-07-26T12:59:44Z",
        updated_at: "2022-11-20T13:27:09Z",
    },
    {
        login: "timd",
        id: 6924,
        node_id: "MDQ6VXNlcjY5MjQ=",
        avatar_url: "https://avatars.githubusercontent.com/u/6924?v=4",
        gravatar_id: "",
        url: "https://api.github.com/users/timd",
        html_url: "https://github.com/timd",
        followers_url: "https://api.github.com/users/timd/followers",
        following_url:
            "https://api.github.com/users/timd/following{/other_user}",
        gists_url: "https://api.github.com/users/timd/gists{/gist_id}",
        starred_url: "https://api.github.com/users/timd/starred{/owner}{/repo}",
        subscriptions_url: "https://api.github.com/users/timd/subscriptions",
        organizations_url: "https://api.github.com/users/timd/orgs",
        repos_url: "https://api.github.com/users/timd/repos",
        events_url: "https://api.github.com/users/timd/events{/privacy}",
        received_events_url:
            "https://api.github.com/users/timd/received_events",
        type: "User",
        site_admin: false,
        name: "Tim Duckett",
        company: null,
        blog: "https://trashpanda.cc",
        location: "Berlin, Deutschland",
        email: null,
        hireable: null,
        bio: "CTO, economicly migratory Inselaffe, Kohlenstoffbasierte Zweibeiner Säugetiere\r\n",
        twitter_username: null,
        public_repos: 136,
        public_gists: 22,
        followers: 108,
        following: 0,
        created_at: "2008-04-12T11:25:16Z",
        updated_at: "2022-11-26T12:23:39Z",
    },
    {
        login: "Alpha",
        id: 15315424,
        node_id: "MDEyOk9yZ2FuaXphdGlvbjE1MzE1NDI0",
        avatar_url: "https://avatars.githubusercontent.com/u/15315424?v=4",
        gravatar_id: "",
        url: "https://api.github.com/users/Alpha",
        html_url: "https://github.com/Alpha",
        followers_url: "https://api.github.com/users/Alpha/followers",
        following_url:
            "https://api.github.com/users/Alpha/following{/other_user}",
        gists_url: "https://api.github.com/users/Alpha/gists{/gist_id}",
        starred_url:
            "https://api.github.com/users/Alpha/starred{/owner}{/repo}",
        subscriptions_url: "https://api.github.com/users/Alpha/subscriptions",
        organizations_url: "https://api.github.com/users/Alpha/orgs",
        repos_url: "https://api.github.com/users/Alpha/repos",
        events_url: "https://api.github.com/users/Alpha/events{/privacy}",
        received_events_url:
            "https://api.github.com/users/Alpha/received_events",
        type: "Organization",
        site_admin: false,
        name: "Alpha",
        company: null,
        blog: "",
        location: "Everywhere",
        email: null,
        hireable: null,
        bio: null,
        twitter_username: null,
        public_repos: 2,
        public_gists: 0,
        followers: 1,
        following: 0,
        created_at: "2015-10-25T23:05:32Z",
        updated_at: "2020-11-29T12:48:23Z",
    },
    {
        login: "beta",
        id: 5000910,
        node_id: "MDQ6VXNlcjUwMDA5MTA=",
        avatar_url: "https://avatars.githubusercontent.com/u/5000910?v=4",
        gravatar_id: "",
        url: "https://api.github.com/users/beta",
        html_url: "https://github.com/beta",
        followers_url: "https://api.github.com/users/beta/followers",
        following_url:
            "https://api.github.com/users/beta/following{/other_user}",
        gists_url: "https://api.github.com/users/beta/gists{/gist_id}",
        starred_url: "https://api.github.com/users/beta/starred{/owner}{/repo}",
        subscriptions_url: "https://api.github.com/users/beta/subscriptions",
        organizations_url: "https://api.github.com/users/beta/orgs",
        repos_url: "https://api.github.com/users/beta/repos",
        events_url: "https://api.github.com/users/beta/events{/privacy}",
        received_events_url:
            "https://api.github.com/users/beta/received_events",
        type: "User",
        site_admin: false,
        name: "Beta Kuang",
        company: "@meican-dev",
        blog: "https://betakuang.me",
        location: "nil",
        email: null,
        hireable: true,
        bio: "Web & app developer",
        twitter_username: "betakuang",
        public_repos: 66,
        public_gists: 43,
        followers: 105,
        following: 44,
        created_at: "2013-07-13T03:21:42Z",
        updated_at: "2022-11-01T05:58:23Z",
    },

    {
        login: "charlie",
        id: 1763,
        node_id: "MDQ6VXNlcjE3NjM=",
        avatar_url: "https://avatars.githubusercontent.com/u/1763?v=4",
        gravatar_id: "",
        url: "https://api.github.com/users/charlie",
        html_url: "https://github.com/charlie",
        followers_url: "https://api.github.com/users/charlie/followers",
        following_url:
            "https://api.github.com/users/charlie/following{/other_user}",
        gists_url: "https://api.github.com/users/charlie/gists{/gist_id}",
        starred_url:
            "https://api.github.com/users/charlie/starred{/owner}{/repo}",
        subscriptions_url: "https://api.github.com/users/charlie/subscriptions",
        organizations_url: "https://api.github.com/users/charlie/orgs",
        repos_url: "https://api.github.com/users/charlie/repos",
        events_url: "https://api.github.com/users/charlie/events{/privacy}",
        received_events_url:
            "https://api.github.com/users/charlie/received_events",
        type: "User",
        site_admin: false,
        name: "Charles Hornberger",
        company: null,
        blog: "",
        location: "Berlin",
        email: null,
        hireable: null,
        bio: null,
        twitter_username: null,
        public_repos: 11,
        public_gists: 9,
        followers: 4,
        following: 0,
        created_at: "2008-02-29T17:24:19Z",
        updated_at: "2022-11-25T13:53:55Z",
    },
]

export default testData
